version: "3.2"

services:
  # Container name
  postgres-cont:
    build:
      context: ${PWD}

    # Open ports for Postgres and Django
    ports:
      - "5432:5432"
      - "8000:8000"

    # Bind mount volumes
    volumes:
      - $PWD/pg-data/:/var/lib/postgresql/data
      - $PWD/:/usr/src/plotlyDashDjango/

    # configure Postgres environment variables
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=testingdb
      - POSTGRES_PASSWORD=12345678

networks:
  postgres-net:
  ipv4_address:
    172.28.1.4

networks:
  postgres-net:
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16